import type {
  Metadata,
} from 'next'
import {
  Roboto,
} from 'next/font/google'
import './globals.scss'
import Footer from '@/shared/ui/footer/Footer'
import {
  AuthProvider,
} from '@/features/auth/providers/AuthProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={roboto.className}
        style={{
          display: 'flex',
          flexDirection: 'column',
          minHeight: '100vh',
        }}
      >
        <main style={{
          flex: 1,
          // background: 'var(--color-bgGray)',
        }}
        >
          <AuthProvider>
            {children}
          </AuthProvider>
        </main>
        <Footer />
      </body>
    </html>
  )
}
