import type {
  Metadata,
} from 'next'
import {
  Roboto,
} from 'next/font/google'
import Header from '@/shared/ui/header/Header'
import SideBar from '@/shared/ui/sidebar/SideBar'
import {
  Container, Grid,
} from '@mui/material'
import GlobalSnackbar from '@/features/notify/ui/GlobalSnackbar'
import {
  AdminContent,
} from '@/widgets/ui/AdminContent'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
})

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className={roboto.className}>
      <Header />
      <Container
        maxWidth="lg"
        sx={{
          display: 'flex',
          justifyContent: 'center',
        }}
      >
        <Grid container spacing={4}>
          <SideBar />
          <AdminContent>
            {children}
          </AdminContent>
        </Grid>
      </Container>

      <GlobalSnackbar />
    </main>
  )
}
